version: '3.8'

services:
  krone-rss:
    build: . # Specifies to build the image from the Dockerfile in the current directory
    container_name: krone-rss
    ports:
      - "8084:8080" # Maps port 8080 of the host to port 8080 of the container
    restart: unless-stopped
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
